###

GET http://localhost:3000/node_api/config/public/componentLayout?name=summary

###

GET http://localhost:3000/node_api/config/public/componentLayout?name=definition

###

GET http://localhost:3000/node_api/config/public/dashboardLayout?name=conceptDashboard