GET http://localhost:3000/node_api/entity/public/propertyType?modelIri=http://endhealth.info/im#AdministrationNote&propIri=http://endhealth.info/im#concept

###

GET http://localhost:3000/node_api/entity/public/propertyType?modelIri=http://endhealth.info/im#AdministrationNote&propIri=http://endhealth.info/im#text

###