GET http://localhost:3000/api/item?id=99
Accept: application/json

###
GET http://localhost:8080/api/query/public/queryIM
content-type: application/json

{
  "name" : "AllowablePropertiesForCovid",
  "description" : "gets the active properties and their subtypes that have a domain which is a super type of covid.",
  "activeOnly" : true,
  "select" : {
    "filter" : {
      "property" : {
        "@id" : "http://www.w3.org/2000/01/rdf-schema#domain"
      },
      "valueConcept" : [ {
        "includeSupertypes" : true,
        "@id" : "http://snomed.info/sct#674814021000119106"
      } ]
    },
    "entityType" : {
      "includeSubtypes" : true,
      "@id" : "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"
    },
    "distinct" : true,
    "property" : [ {
      "@id" : "http://endhealth.info/im#id"
    }, {
      "@id" : "http://endhealth.info/im#code"
    }, {
      "@id" : "http://www.w3.org/2000/01/rdf-schema#label"
    } ]
  }
}

###

GET http://localhost:8080/api/query/public/queryIM
content-type: application/json

{
  "name": "AllowableValuesForPropertyClinicalCourse",
  "description": "Gets the allowable values (range) for the 'Clinical Course' property.",
  "activeOnly": true,
  "select": {
    "filter": {
      "property": {
        "@id": "http://www.w3.org/2000/01/rdf-schema#range"
      },
      "inverseOf": true,
      "valueConcept": [
        {
          "includeSupertypes": true,
          "@id": "http://snomed.info/sct#263502005"
        }
      ]
    },
    "distinct": true,
    "property": [
      {
        "@id": "http://endhealth.info/im#id"
      },
      {
        "@id": "http://endhealth.info/im#code"
      },
      {
        "@id": "http://www.w3.org/2000/01/rdf-schema#label"
      }
    ]
  }
}

###

GET http://localhost:3000/node_api/query/public/run?iri=http://endhealth.info/im#Q_RegisteredGMS

###

GET http://localhost:3000/node_api/query/public/run?iri=urn%3Auuid%3A6d517466-813b-46a8-b848-aaf5a4fbdcbf

###

GET http://localhost:3000/node_api/query/public/run?iri=urn%3Auuid%3A7d9a0a98-4df8-4748-8940-061a5148293c

###

GET http://localhost:3000/node_api/query/public/getSQL?iri=http://endhealth.info/im#Q_RegisteredGMS

###

GET http://localhost:3000/node_api/query/public/getSQL?iri=urn%3Auuid%3A6d517466-813b-46a8-b848-aaf5a4fbdcbf

###

GET http://localhost:3000/node_api/query/public/getSQL?iri=urn%3Auuid%3A951b62db-4e81-4fcd-8cf7-0e71c28d30e9

###

POST http://localhost:3000/node_api/validation/public/validate?iri=http://endhealth.info/im#Validation_hasParent
Content-Type: application/json

{
   "http://endhealth.info/im#isContainedIn": [{ "@id": "http://endhealth.info/im#IMQuery", "name": "Test" }]
}

###

POST http://127.0.0.1:8082/nodeapi/node_api/query/public/quickQuery
Content-Type: application/json

{
  "http://endhealth.info/im#Patient": {
    "output": [
      "http://endhealth.info/im#fullName",
      "http://endhealth.info/im#age",
      "http://endhealth.info/im#nhsNumber"
    ],
    "filters": {
      "http://endhealth.info/im#fullName": {
        "stringPattern": "B*"
      },
      "http://endhealth.info/im#age": {
        "numberRange": {
          "from": {
            "comparator": ">",
            "value": "7"
          },
          "to": {
            "comparator": "<=",
            "value": "18"
          }
        }
      }
    }
  },
  "http://endhealth.info/im#Observation": {
    "output": [
      "http://endhealth.info/im#effectiveDate",
      "http://endhealth.info/im#hasPractitioner",
      "http://endhealth.info/im#typeOfObservation"
    ],
    "filters": {
      "http://endhealth.info/im#effectiveDate": {
        "dateRange": {
          "from": "2008-01-01",
          "to": "2008-12-31"
        }
      }
    }
  }
}

###

GET http://127.0.0.1:3000/node_api/query/public/queryDefinitionDisplay?iri=http:%2F%2Fendhealth.info%2Fim%23CSET_OralNSAIDs

###

GET http://127.0.0.1:3000/node_api/github/public/latestRelease/?repositoryName=IMViewer

###

POST http://127.0.0.1:8080/api/entity/public/search
Content-Type: application/json

{"termFilter":"current registration","sortBy":0,"page":1,"size":100,"schemeFilter":[],"statusFilter":[],"typeFilter":[],"sortField":"weighting","sortDirection":"DESC"}

###

GET http://127.0.0.1:3000/node_api/fhir/r4/ValueSet/http:%2F%2Fendhealth.info%2Fceg%2Fqry%23CSET_EthnicCategoryCEG16

###

GET http://127.0.0.1:3000/node_api/fhir/r4/ValueSet/$expand?url=http://endhealth.info/ceg/qry#CSET_EthnicCategoryCEG16

###

GET http://127.0.0.1:3000/node_api/fhir/r4/ValueSet?iri=http://endhealth.info/im#CSET_EthnicCategoryCEG16_A&expand=true

###

GET http://127.0.0.1:3000/node_api/fhir/r4/ValueSet?iri=http://endhealth.info/im#CSET_Covid5&expand=true


###

GET http://127.0.0.1:3000/node_api/fhir/r4/ValueSet?iri=http://endhealth.info/im#VSET_FamilyHistory&expand=true

###

POST http://127.0.0.1:8080/api/set/public/query/ecl
Content-Type: application/json

{
  "where": {
    "from": [
      {
        "@id": "http://snomed.info/sct#102584008",
        "name": "Unequal blood pressure in arms (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#162758008",
        "name": "On examination - height within 10% average (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#162759000",
        "name": "On examination - height 10-20% over average (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#162761009",
        "name": "On examination - loss of height (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#162766004",
        "name": "On examination - weight within 10% ideal (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#162769006",
        "name": "On examination - Underweight (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#162879003",
        "name": "Height and weight (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#162986007",
        "name": "On examination - pulse rate (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#163020007",
        "name": "On examination - blood pressure reading (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#163023009",
        "name": "On examination - blood pressure reading low (disorder)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#164300005",
        "name": "On examination - temperature normal (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#164303007",
        "name": "On examination - temperature elevated (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#198081000000101",
        "name": "Ambulatory systolic blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#198091000000104",
        "name": "Ambulatory diastolic blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#238131007",
        "name": "Overweight (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#248349002",
        "name": "Percentage weight loss (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#248350002",
        "name": "Reference weight (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#248358009",
        "name": "Weight for height (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#315612005",
        "name": "Target systolic blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#315613000",
        "name": "Target diastolic blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#335661000000109",
        "name": "Self measured blood pressure reading (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#35425004",
        "name": "Normal body mass index (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#363806002",
        "name": "Weight loss (amount) (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#364589006",
        "name": "Birth weight (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#400974009",
        "name": "Standing systolic blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#400975005",
        "name": "Standing diastolic blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#407554009",
        "name": "Sitting systolic blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#407555005",
        "name": "Sitting diastolic blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#407556006",
        "name": "Lying systolic blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#407557002",
        "name": "Lying diastolic blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#424927000",
        "name": "Body weight with shoes (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#425024002",
        "name": "Body weight without shoes (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#429745009",
        "name": "Diurnal variation of peak expiratory flow rate (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#445541000",
        "name": "Dry body weight (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#446974000",
        "name": "Body mass index centile (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#48499001",
        "name": "Increased body mass index (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#6497000",
        "name": "Decreased body mass index (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#715456008",
        "name": "Percentage median body mass index for age and sex (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#716579001",
        "name": "Baseline systolic blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#716632005",
        "name": "Baseline diastolic blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#72313002",
        "name": "Systolic arterial pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#723232008",
        "name": "Average blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#763131000000100",
        "name": "Peak expiratory flow rate after exercise (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#78564009",
        "name": "Heart rate measured at systemic artery (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#814081000000101",
        "name": "Diastolic blood pressure centile (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#814101000000107",
        "name": "Systolic blood pressure centile (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#838441000000103",
        "name": "Target body mass index (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#846931000000101",
        "name": "Baseline body mass index (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#852451000000103",
        "name": "Maximum body mass index (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#852461000000100",
        "name": "Minimum body mass index (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#87179004",
        "name": "Arterial pulse pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#920141000000102",
        "name": "Child body mass index less than 0.4th centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#920161000000101",
        "name": "Child body mass index 0.4th-1.9th centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#920181000000105",
        "name": "Child body mass index on 2nd centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#920201000000109",
        "name": "Child body mass index 3rd-8th centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#920231000000103",
        "name": "Child body mass index on 9th centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#920251000000105",
        "name": "Child body mass index 10th-24th centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#920271000000101",
        "name": "Child body mass index on 25th centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#920291000000102",
        "name": "Child body mass index 26th-49th centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#920311000000101",
        "name": "Child body mass index on 50th centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#920841000000108",
        "name": "Child body mass index 51st-74th centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#920931000000108",
        "name": "Child body mass index on 75th centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#920951000000101",
        "name": "Child body mass index 76th-90th centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#920971000000105",
        "name": "Child body mass index on 91st centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#920991000000109",
        "name": "Child body mass index 92nd-97th centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#921011000000105",
        "name": "Child body mass index on 98th centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#921031000000102",
        "name": "Child body mass index 98.1st-99.6th centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#921051000000109",
        "name": "Child body mass index greater than 99.6th centile (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#928021000000108",
        "name": "Baseline blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#163035008",
        "name": "Sitting blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#163034007",
        "name": "Standing blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#60621009",
        "name": "Body mass index (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#163033001",
        "name": "Lying blood pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#1091811000000102",
        "name": "Diastolic arterial pressure (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#758931000000104",
        "name": "Height and weight measurement for National Child Measurement Programme (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#248333004",
        "name": "Standing height (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#27113001",
        "name": "Body weight (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#697930002",
        "name": "Labile hypertension due to being in a clinical environment (disorder)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#248348005",
        "name": "Percentage weight gain (observable entity)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#86651002",
        "name": "Pulse fast (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#42177007",
        "name": "Pulse slow (finding)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#313005002",
        "name": "On examination - blood pressure reading: no postural drop (situation)",
        "includeSubtypes": true
      },
      {
        "@id": "http://snomed.info/sct#251074006",
        "name": "Non-invasive mean arterial pressure (observable entity)",
        "includeSubtypes": true
      }
    ]
  }
}
