GET http://localhost:3000/node_api/prov/public/history?url=http://endhealth.info/im#Q_RegisteredGMS

###

GET http://localhost:3000/node_api/prov/public/history?url=http://endhealth.info/im#VSET_FHIR

###

GET http://localhost:3000/node_api/prov/public/history?url=http://endhealth.info/im#HealthDataModel

###


