GET http://127.0.0.1:3000/node_api/fhir/r4/ValueSet?url=http://apiqcodes.org/qcodes#QPredict_331

###

GET http://127.0.0.1:3000/node_api/fhir/r4/ValueSet/$expand?url=http://apiqcodes.org/qcodes#QPredict_331

###

GET http://127.0.0.1:3000/node_api/fhir/r4/ValueSet?url=http://apiqcodes.org/qcodes#QCodeGroup_21

###

GET http://127.0.0.1:3000/node_api/fhir/r4/ValueSet/$expand?url=http://apiqcodes.org/qcodes#QCodeGroup_21

###

GET https://dev.endhealth.co.uk/nodeapi/node_api/fhir/r4/ValueSet?url=http://apiqcodes.org/qcodes#QPredict_331

###

GET https://dev.endhealth.co.uk/nodeapi/node_api/fhir/r4/ValueSet/$expand?url=http://apiqcodes.org/qcodes#QPredict_331

###

GET https://dev.endhealth.co.uk/nodeapi/node_api/fhir/r4/ValueSet?url=http://apiqcodes.org/qcodes#QCodeGroup_21

###

GET https://dev.endhealth.co.uk/nodeapi/node_api/fhir/r4/ValueSet/$expand?url=http://apiqcodes.org/qcodes#QCodeGroup_21
