import { IM, RDF, RDFS, SHACL } from "../vocabulary";

const ENTITY_TYPES = [IM.CONCEPT, IM.VALUE_SET, IM.CONCEPT_SET, SHACL.NODESHAPE, IM.DATAMODEL_PROPERTY, IM.QUERY, RDFS.CLASS, RDF.PROPERTY, IM.FOLDER];

export default [...ENTITY_TYPES];
