version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/im_library" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/node_api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/ui" 
    schedule:
      interval: "weekly"
