version: 0.0
os: linux
files:
  - source: /ui/dist
    destination: /usr/share/nginx/directory
  - source: /node_api/dist
    destination: /opt/nodeapi/
  - source: /node_api/package.json
    destination: /opt/nodeapi/
hooks:
  BeforeInstall:
    - location: aws_scripts/cleanup
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws_scripts/deploy
      timeout: 300
      runas: root
