import com.github.gradle.node.pnpm.task.PnpmTask

/*
 * This file was generated by the Gradle "init" task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/6.7.1/samples
 */
plugins {
    id("base")
    id("com.github.node-gradle.node")
    id("org.sonarqube").version("4.4.1.3373")
}

sonar {
    properties {
        property("sonar.organization", "endeavourhealth-discovery")
        property("sonar.token", System.getenv("SONAR_LOGIN"))
        property("sonar.host.url", "https://sonarcloud.io")
        property("sonar.projectKey", "endeavourhealth-discovery_IMDirectory")
        property("sonar.projectName", "IMDirectory")
        property("sonar.sources", "src/composables,src/helpers,src/stores,src/services")
        property("sonar.exclusions", "**/index.ts,**/*.d.ts,**/node_modules/**")
        property("sonar.tests", "tests")
        property("sonar.test.inclusions", "**/*.spec.ts,**/*.spec.js")
        property("sonar.javascript.lcov.reportPaths", "coverage/lcov.info")
    }
}

tasks.findByName("pnpmInstall")?.doNotTrackState("Otherwise fails on optional FA Pro dependency")

tasks.register<PnpmTask>("pnpmBuild") {
    dependsOn(tasks.findByName("pnpmInstall"))
    args = listOf("run", "build")
}

tasks.register<PnpmTask>("pnpmTest") {
    dependsOn(tasks.findByName("pnpmInstall"))
    args = listOf("run", "test:coverage")
}

tasks.assemble {
    dependsOn(tasks.findByName("pnpmBuild"))
}

tasks.check {
    dependsOn(tasks.findByName("pnpmTest"))
}

tasks.clean {
    doLast {
        file("coverage").deleteRecursively()
        file("dist").deleteRecursively()
    }
}

if (System.getenv("ENV") == "prod") {
    tasks.build {
        finalizedBy(sonar)
    }
}
