version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - echo Node install
      - rm /usr/local/bin/node
      - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      - sudo apt-get install nodejs
      - node -v
  build:
    commands:
      - chmod +x aws_scripts/build.sh
      - aws_scripts/build.sh
  post_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - aws_scripts/cleanup
    - aws_scripts/deploy
    - ui/dist/**/*
    - node_api/dist/**/*
    - node_api/package.json
