version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - echo Node install
      - rm /usr/local/bin/node
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      - sudo apt-get install nodejs
      - node -v
      - export NODE_OPTIONS=--max-old-space-size=4096
      - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
      - npm config set "//npm.fontawesome.com/:_authToken" $VITE_FONT_AWESOME_PACKAGE_TOKEN
      - npm i -g pnpm
  build:
    commands:
      - chmod +x aws_scripts/build.sh
      - aws_scripts/build.sh
  post_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - aws_scripts/cleanup
    - aws_scripts/deploy
    - ui/dist/**/*
    - node_api/dist/**/*
    - node_api/package.json
