sonar.organization=endeavourhealth-discovery
sonar.projectKey=IMDirectory
sonar.projectName=IMDirectory
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.exclusions=**/node_modules/**,*.yaml,*.json
