// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class CODE_TEMPLATE {
  public static readonly DOMAIN = "http://endhealth.info/";
  public static readonly NAMESPACE = CODE_TEMPLATE.DOMAIN + "codeTemplate#";
  public static readonly PREFIX = "cTemp";
  public static readonly WRAPPER = CODE_TEMPLATE.NAMESPACE + "wrapper";
  public static readonly DATATYPE_MAP = CODE_TEMPLATE.NAMESPACE + "datatypeMap";
  public static readonly EXTENSION = CODE_TEMPLATE.NAMESPACE + "extension";
}
