// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {IM} from "@/vocabulary/IM";
import {RDF} from "@/vocabulary/RDF";
import {RDFS} from "@/vocabulary/RDFS";
import {Namespace} from "@/vocabulary/Namespace";

export class CodeTemplate {

  public static readonly DOMAIN = "http://endhealth.info/"
  public static readonly PREFIX = "cTemp"
  public static readonly WRAPPER = Namespace.IM_CODE_TEMPLATE + "wrapper"
  public static readonly LABEL = RDFS.LABEL
  public static readonly DEFINITION = IM.DEFINITION
  public static readonly TYPE = RDF.TYPE
  public static readonly DATATYPE_MAP = Namespace.IM_CODE_TEMPLATE + "datatypeMap"
  public static readonly EXTENSION = Namespace.IM_CODE_TEMPLATE + "extension"
  public static readonly INCLUDE_COMPLEX_TYPES = Namespace.IM_CODE_TEMPLATE + "includeComplexTypes"
}
