// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {Namespace} from "@/vocabulary/Namespace";

export class COMPONENT {

  public static readonly DOMAIN = "http://endhealth.info/im#"
  public static readonly TAB_LAYOUT = Namespace.IM_COMPONENT + "TabLayout"
  public static readonly TEXT_DISPLAY = Namespace.IM_COMPONENT + "textDisplay"
  public static readonly TEXT_INPUT = Namespace.IM_COMPONENT + "textInput"
  public static readonly HTML_INPUT = Namespace.IM_COMPONENT + "htmlInput"
  public static readonly ENTITY_MULTI_SEARCH = Namespace.IM_COMPONENT + "entityMultiSearch"
  public static readonly ENTITY_SEARCH = Namespace.IM_COMPONENT + "entitySearch"
  public static readonly ENTITY_COMBOBOX = Namespace.IM_COMPONENT + "entityComboBox"
  public static readonly ENTITY_DROPDOWN = Namespace.IM_COMPONENT + "entityDropdown"
  public static readonly ARRAY_BUILDER = Namespace.IM_COMPONENT + "arrayBuilder"
  public static readonly ENTITY_AUTO_COMPLETE = Namespace.IM_COMPONENT + "entityAutoComplete"
  public static readonly MEMBERS_BUILDER = Namespace.IM_COMPONENT + "membersBuilder"
  public static readonly COMPONENT_GROUP = Namespace.IM_COMPONENT + "componentGroup"
  public static readonly PROPERTY_BUILDER = Namespace.IM_COMPONENT + "propertyBuilder"
  public static readonly SET_DEFINITION_BUILDER = Namespace.IM_COMPONENT + "SetDefinitionBuilder"
  public static readonly QUERY_DEFINITION_BUILDER = Namespace.IM_COMPONENT + "QueryDefinitionBuilder"
  public static readonly TOGGLEABLE = Namespace.IM_COMPONENT + "ToggleableComponent"
  public static readonly HORIZONTAL_LAYOUT = Namespace.IM_COMPONENT + "HorizontalLayout"
  public static readonly VERTICAL_LAYOUT = Namespace.IM_COMPONENT + "VerticalLayout"
  public static readonly DROPDOWN_TEXT_INPUT_CONCATENATOR = Namespace.IM_COMPONENT + "dropdownTextInputConcatenator"
  public static readonly ROLE_GROUP_BUILDER = Namespace.IM_COMPONENT + "roleGroupBuilder"
  public static readonly TERM_CODE_EDITOR = Namespace.IM_COMPONENT + "termCodeEditor"
  public static readonly TEXT_DROPDOWN = Namespace.IM_COMPONENT + "textDropdown"
  public static readonly ENTITY_DISPLAY = Namespace.IM_COMPONENT + "entityDisplay"
  public static readonly IRI_BUILDER = Namespace.IM_COMPONENT + "iriBuilder"
  public static readonly AUTOCOMPLETE_SEARCH_BAR_WRAPPER = Namespace.IM_COMPONENT + "autocompleteSearchBarWrapper"
  public static readonly SUBSET_BUILDER = Namespace.IM_COMPONENT + "subsetBuilder"
}
