// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class COMPONENT {
  public static readonly DOMAIN = "http://endhealth.info/im#";
  public static readonly NAMESPACE = COMPONENT.DOMAIN + "Component_";
  public static readonly TAB_LAYOUT = COMPONENT.NAMESPACE + "TabLayout";
  public static readonly TEXT_DISPLAY = COMPONENT.NAMESPACE + "textDisplay";
  public static readonly TEXT_INPUT = COMPONENT.NAMESPACE + "textInput";
  public static readonly HTML_INPUT = COMPONENT.NAMESPACE + "htmlInput";
  public static readonly ENTITY_MULTI_SEARCH = COMPONENT.NAMESPACE + "entityMultiSearch";
  public static readonly ENTITY_SEARCH = COMPONENT.NAMESPACE + "entitySearch";
  public static readonly ENTITY_COMBOBOX = COMPONENT.NAMESPACE + "entityComboBox";
  public static readonly ENTITY_DROPDOWN = COMPONENT.NAMESPACE + "entityDropdown";
  public static readonly ARRAY_BUILDER = COMPONENT.NAMESPACE + "arrayBuilder";
  public static readonly ENTITY_AUTO_COMPLETE = COMPONENT.NAMESPACE + "entityAutoComplete";
  public static readonly MEMBERS_BUILDER = COMPONENT.NAMESPACE + "membersBuilder";
  public static readonly COMPONENT_GROUP = COMPONENT.NAMESPACE + "componentGroup";
  public static readonly PROPERTY_BUILDER = COMPONENT.NAMESPACE + "propertyBuilder";
  public static readonly SET_DEFINITION_BUILDER = COMPONENT.NAMESPACE + "SetDefinitionBuilder";
  public static readonly QUERY_DEFINITION_BUILDER = COMPONENT.NAMESPACE + "QueryDefinitionBuilder";
  public static readonly TOGGLEABLE = COMPONENT.NAMESPACE + "ToggleableComponent";
  public static readonly HORIZONTAL_LAYOUT = COMPONENT.NAMESPACE + "HorizontalLayout";
  public static readonly VERTICAL_LAYOUT = COMPONENT.NAMESPACE + "VerticalLayout";
  public static readonly DROPDOWN_TEXT_INPUT_CONCATENATOR = COMPONENT.NAMESPACE + "dropdownTextInputConcatenator";
  public static readonly ROLE_GROUP_BUILDER = COMPONENT.NAMESPACE + "roleGroupBuilder";
  public static readonly TERM_CODE_EDITOR = COMPONENT.NAMESPACE + "termCodeEditor";
  public static readonly TEXT_DROPDOWN = COMPONENT.NAMESPACE + "textDropdown";
  public static readonly ENTITY_DISPLAY = COMPONENT.NAMESPACE + "entityDisplay";
  public static readonly IRI_BUILDER = COMPONENT.NAMESPACE + "iriBuilder";
  public static readonly AUTOCOMPLETE_SEARCH_BAR_WRAPPER = COMPONENT.NAMESPACE + "autocompleteSearchBarWrapper";
  public static readonly SUBSET_BUILDER = COMPONENT.NAMESPACE + "subsetBuilder";
}
