// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class CONFIG {
  public static readonly NAMESPACE = "http://endhealth.info/config#";
  public static readonly DOMAIN = "http://endhealth.info/";
  public static readonly PREFIX = "cfg";
  public static readonly IMDIRECTORY_LATEST_RELEASE = CONFIG.NAMESPACE + "IMDirectoryLatestRelease";
  public static readonly IMDIRECTORY_ALL_RELEASES = CONFIG.NAMESPACE + "IMDirectoryAllReleases";
  public static readonly MONITORING = CONFIG.NAMESPACE + "monitoring";
}
