// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {Namespace} from "@/vocabulary/Namespace";
import {IM} from "@/vocabulary/IM";
import {RDFS} from "@/vocabulary/RDFS";

export class CONFIG {

  public static readonly DOMAIN = "http://endhealth.info/"
  public static readonly PREFIX = "cfg"
  public static readonly LABEL = RDFS.LABEL
  public static readonly HAS_CONFIG = IM.HAS_CONFIG
  public static readonly COMMENT = RDFS.COMMENT
  public static readonly IMDIRECTORY_LATEST_RELEASE = Namespace.CONFIG + "IMDirectoryLatestRelease"
  public static readonly IMDIRECTORY_ALL_RELEASES = Namespace.CONFIG + "IMDirectoryAllReleases"
  public static readonly MONITORING = Namespace.CONFIG + "monitoring"
}
