// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {Namespace} from "@/vocabulary/Namespace";

export class EDITOR {

  public static readonly DOMAIN = "http://endhealth.info/im#"
  public static readonly CONCEPT_SHAPE = Namespace.IM_EDITOR + "ConceptShape"
  public static readonly CONCEPT_SET_SHAPE = Namespace.IM_EDITOR + "ConceptSetShape"
  public static readonly VALUE_SET_SHAPE = Namespace.IM_EDITOR + "ValueSetShape"
  public static readonly FOLDER_SHAPE = Namespace.IM_EDITOR + "FolderShape"
  public static readonly DATA_MODEL_SHAPE = Namespace.IM_EDITOR + "DataModelShape"
  public static readonly COHORT_QUERY_SHAPE = Namespace.IM_EDITOR + "CohortQueryShape"
  public static readonly PROPERTY_SHAPE = Namespace.IM_EDITOR + "PropertyShape"
}
