// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class EDITOR {
  public static readonly DOMAIN = "http://endhealth.info/im#";
  public static readonly NAMESPACE = EDITOR.DOMAIN + "Editor_";
  public static readonly CONCEPT_SHAPE = EDITOR.NAMESPACE + "ConceptShape";
  public static readonly CONCEPT_SET_SHAPE = EDITOR.NAMESPACE + "ConceptSetShape";
  public static readonly VALUE_SET_SHAPE = EDITOR.NAMESPACE + "ValueSetShape";
  public static readonly FOLDER_SHAPE = EDITOR.NAMESPACE + "FolderShape";
  public static readonly DATA_MODEL_SHAPE = EDITOR.NAMESPACE + "DataModelShape";
  public static readonly COHORT_QUERY_SHAPE = EDITOR.NAMESPACE + "CohortQueryShape";
  public static readonly PROPERTY_SHAPE = EDITOR.NAMESPACE + "PropertyShape";
}
