// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {IM} from "@/vocabulary/IM";
import {SHACL} from "@/vocabulary/SHACL";

export class EntityType {

  public static readonly QUERY = IM.QUERY
  public static readonly NODESHAPE = SHACL.NODESHAPE
}
