// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class FHIR {
  public static readonly DOMAIN = "http://hl7.org/fhir/";
  public static readonly PREFIX = "fhir";
  public static readonly DSTU2 = "http://hl7.org/2-0/fhir/StructureDefinition#";
  public static readonly GRAPH_FHIR = FHIR.DOMAIN;
  public static readonly VALUESET_FOLDER = "http://endhealth.info/im#VSET_FHIR";
}
