// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class GRAPH {
  public static readonly FHIR = "http://hl7.org/fhir/";
  public static readonly SMARTLIFE = "http://smartlifehealth.info/smh#";
  public static readonly QOF = "http://endhealth.info/qof#";
  public static readonly DISCOVERY = "http://endhealth.info/im#";
  public static readonly BNF = "http://endhealth.info/bnf#";
  public static readonly ICD10 = "http://endhealth.info/icd10#";
  public static readonly EMIS = "http://endhealth.info/emis#";
  public static readonly CPRD_MED = "http://endhealth.info/cprdm#";
  public static readonly CPRD_PROD = "http://endhealth.info/cprdp#";
  public static readonly OPCS4 = "http://endhealth.info/opcs4#";
  public static readonly TPP = "http://endhealth.info/tpp#";
  public static readonly ODS = "http://endhealth.info/ods#";
  public static readonly PRSB = "http://endhealth.info/prsb#";
  public static readonly KINGS_APEX = "http://endhealth.info/kpax#";
  public static readonly KINGS_WINPATH = "http://endhealth.info/kwp#";
  public static readonly VISION = "http://endhealth.info/vis#";
  public static readonly READ2 = "http://endhealth.info/read2#";
  public static readonly BARTS_CERNER = "http://endhealth.info/bc#";
  public static readonly NHSDD_ETHNIC_2001 = "http://endhealth.info/nhsethnic2001#";
  public static readonly IM1 = "http://endhealth.info/im1#";
  public static readonly ENCOUNTERS = "http://endhealth.info/enc#";
  public static readonly CONFIG = "http://endhealth.info/config#";
  public static readonly CEG = "http://endhealth.info/ceg#";
  public static readonly NHS_TFC = "http://endhealth.info/nhstfc#";
  public static readonly STATS = "http://endhealth.info/stats#";
  public static readonly DELTAS = "http://endhealth.info/deltas#";
  public static readonly PROV = "http://endhealth.info/prov#";
  public static readonly QUERY = "http://endhealth.info/query#";
  public static readonly REPORTS = "http://endhealth.info/reports#";
  public static readonly OPS_ROLES = "https://directory.spineservices.nhs.uk/STU3/CodeSystem/ODSAPI-OrganizationRole-1#";
  public static readonly XS = "http://www.w3.org/2001/XMLSchema#";
}
