// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator



export class Graph {

  public static readonly IM = "http://endhealth.info/im#"
  public static readonly PROV = "http://endhealth.info/prov#"
  public static readonly USER = "http://endhealth.info/user#"
  public static readonly WORKFLOW = "http://endhealth.info/workflow#"
  public static readonly CONFIG = "http://endhealth.info/config#"
  public static readonly SMARTLIFE = "http://smartlifehealth.info/smh#"
}
