// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class IM_FUNCTION {
  public static readonly DOMAIN = "http://endhealth.info/";
  public static readonly NAMESPACE = IM_FUNCTION.DOMAIN + "im#Function_";
  public static readonly SNOMED_CONCEPT_GENERATOR = IM_FUNCTION.NAMESPACE + "SnomedConceptGenerator";
  public static readonly LOCAL_NAME_RETRIEVER = IM_FUNCTION.NAMESPACE + "LocalNameRetriever";
  public static readonly GET_ADDITIONAL_ALLOWABLE_TYPES = IM_FUNCTION.NAMESPACE + "GetAdditionalAllowableTypes";
  public static readonly GET_LOGIC_OPTIONS = IM_FUNCTION.NAMESPACE + "GetLogicOptions";
  public static readonly GET_SET_EDITOR_IRI_SCHEMES = IM_FUNCTION.NAMESPACE + "GetSetEditorIriSchemes";
  public static readonly IM1_SCHEME_OPTIONS = IM_FUNCTION.NAMESPACE + "IM1SchemeOptions";
  public static readonly SCHEME_FROM_IRI = IM_FUNCTION.NAMESPACE + "SchemeFromIri";
  public static readonly GET_USER_EDITABLE_SCHEMES = IM_FUNCTION.NAMESPACE + "GetUserEditableSchemes";
  public static readonly IS_TYPE = IM_FUNCTION.NAMESPACE + "IsType";
  public static readonly ALLOWABLE_PROPERTIES = IM_FUNCTION.NAMESPACE + "AllowableProperties";
  public static readonly ALLOWABLE_RANGES = IM_FUNCTION.NAMESPACE + "AllowableRanges";
  public static readonly ALLOWABLE_PROPERTY_VALUES = IM_FUNCTION.NAMESPACE + "AllowablePropertyValues";
}
