// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {Namespace} from "@/vocabulary/Namespace";

export class IM_FUNCTION {

  public static readonly DOMAIN = "http://endhealth.info/"
  public static readonly SNOMED_CONCEPT_GENERATOR = Namespace.FUNCTION + "SnomedConceptGenerator"
  public static readonly LOCAL_NAME_RETRIEVER = Namespace.FUNCTION + "LocalNameRetriever"
  public static readonly GET_ADDITIONAL_ALLOWABLE_TYPES = Namespace.FUNCTION + "GetAdditionalAllowableTypes"
  public static readonly GET_LOGIC_OPTIONS = Namespace.FUNCTION + "GetLogicOptions"
  public static readonly GET_SET_EDITOR_IRI_SCHEMES = Namespace.FUNCTION + "GetSetEditorIriSchemes"
  public static readonly IM1_SCHEME_OPTIONS = Namespace.FUNCTION + "IM1SchemeOptions"
  public static readonly SCHEME_FROM_IRI = Namespace.FUNCTION + "SchemeFromIri"
  public static readonly GET_USER_EDITABLE_SCHEMES = Namespace.FUNCTION + "GetUserEditableSchemes"
  public static readonly IS_TYPE = Namespace.FUNCTION + "IsType"
  public static readonly ALLOWABLE_PROPERTIES = Namespace.FUNCTION + "AllowableProperties"
  public static readonly ALLOWABLE_RANGES = Namespace.FUNCTION + "AllowableRanges"
  public static readonly ALLOWABLE_PROPERTY_VALUES = Namespace.FUNCTION + "AllowablePropertyValues"
}
