// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator



export class ImportType {

  public static readonly SNOMED = "snomed"
  public static readonly SKIP_TCT = "tct"
  public static readonly SKIP_SEARCH = "search"
  public static readonly FHIR = "fhir"
  public static readonly SMARTLIFE = "smartlifequery"
  public static readonly QOF = "qof"
  public static readonly CORE = "core"
  public static readonly SINGLE_FILE = "singlefile"
  public static readonly BNF = "bnf"
  public static readonly ICD10 = "icd10"
  public static readonly EMIS = "emis"
  public static readonly CPRD_MED = "cprd"
  public static readonly OPCS4 = "opcs4"
  public static readonly TPP = "tpp"
  public static readonly ODS = "ods"
  public static readonly PRSB = "prsb"
  public static readonly KINGS_APEX = "kingsapex"
  public static readonly KINGS_WINPATH = "kingswinpath"
  public static readonly VISION = "vision"
  public static readonly BARTS_CERNER = "barts"
  public static readonly IM1 = "imv1"
  public static readonly ENCOUNTERS = "encounters"
  public static readonly CONFIG = "config"
  public static readonly CEG = "ceg"
  public static readonly NHS_TFC = "nhstfc"
  public static readonly DELTAS = "deltas"
  public static readonly QUERY = "corequery"
  public static readonly QR = "qcodegroups"
}
