// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator



export class MAP {

  public static readonly DOMAIN = "http://endhealth.info/"
  public static readonly PREFIX = "map"
}
