// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator



export class ODS {

  public static readonly BASE_NAMESPACE = "https://directory.spineservices.nhs.uk/STU3/CodeSystem/ODSAPI-"
  public static readonly ORGANISATION_ROLE_TYPE = ODS.BASE_NAMESPACE + "OrganizationRole-1#ODS_RoleType"
  public static readonly ORGANISATION_RELATIONSHIP = ODS.BASE_NAMESPACE + "OrganizationRelationship-1#ODS_Relationship"
  public static readonly ORGANISATION_RECORD_CLASS = ODS.BASE_NAMESPACE + "OrganizationRecordClass-1#ODS_RecordClass"
}
