// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {IM} from "@/vocabulary/IM";
import {RDF} from "@/vocabulary/RDF";
import {RDFS} from "@/vocabulary/RDFS";

export class OpenSearch {

  public static readonly NAME = RDFS.LABEL
  public static readonly DESCRIPTION = RDFS.COMMENT
  public static readonly CODE = IM.CODE
  public static readonly STATUS = IM.HAS_STATUS
  public static readonly ALTERNATIVE_CODE = IM.ALTERNATIVE_CODE
  public static readonly SCHEME = IM.HAS_SCHEME
  public static readonly TYPE = RDF.TYPE
  public static readonly USAGE_TOTAL = IM.USAGE_TOTAL
  public static readonly BINDING = IM.BINDING
  public static readonly TERM_CODE = IM.HAS_TERM_CODE
  public static readonly DOMAIN = RDFS.DOMAIN
}
