// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class OWL {
  public static readonly NAMESPACE = "http://www.w3.org/2002/07/owl#";
  public static readonly PREFIX = "owl";
  public static readonly THING = OWL.NAMESPACE + "Thing";
  public static readonly CLASS = OWL.NAMESPACE + "Class";
  public static readonly EQUIVALENT_CLASS = OWL.NAMESPACE + "equivalentClass";
  public static readonly INTERSECTION_OF = OWL.NAMESPACE + "intersectionOf";
  public static readonly UNION_OF = OWL.NAMESPACE + "unionOf";
  public static readonly RESTRICTION = OWL.NAMESPACE + "Restriction";
  public static readonly ON_PROPERTY = OWL.NAMESPACE + "onProperty";
  public static readonly ON_CLASS = OWL.NAMESPACE + "onClass";
  public static readonly SOME_VALUES_FROM = OWL.NAMESPACE + "someValuesFrom";
  public static readonly ALL_VALUES_FROM = OWL.NAMESPACE + "allValuesFrom";
  public static readonly OBJECT_PROPERTY = OWL.NAMESPACE + "ObjectProperty";
  public static readonly DATATYPE_PROPERTY = OWL.NAMESPACE + "DatatypeProperty";
  public static readonly ANNOTATION_PROPERTY = OWL.NAMESPACE + "AnnotationProperty";
  public static readonly INVERSE_OF = OWL.NAMESPACE + "inverseOf";
  public static readonly INVERSE_OBJECT_PROPERTY = OWL.NAMESPACE + "inverseOf";
  public static readonly PROPERTY_CHAIN = OWL.NAMESPACE + "propertyChainAxiom";
  public static readonly TRANSITIVE = OWL.NAMESPACE + "TransitiveProperty";
  public static readonly FUNCTIONAL = OWL.NAMESPACE + "FunctionalProperty";
  public static readonly SYMMETRIC = OWL.NAMESPACE + "SymmetricProperty";
  public static readonly REFLEXIVE = OWL.NAMESPACE + "ReflexiveProperty";
  public static readonly ON_DATATYPE = OWL.NAMESPACE + "onDatatype";
  public static readonly WITH_RESTRICTIONS = OWL.NAMESPACE + "withRestrictions";
  public static readonly MAX_CARDINALITY = OWL.NAMESPACE + "maxCardinality";
  public static readonly MIN_CARDINALITY = OWL.NAMESPACE + "minCardinality";
  public static readonly ON_DATA_RANGE = OWL.NAMESPACE + "onDataRange";
  public static readonly HAS_VALUE = OWL.NAMESPACE + "hasValue";
  public static readonly COMPLEMENT_OF = OWL.NAMESPACE + "complementOf";
  public static readonly ONE_OF = OWL.NAMESPACE + "oneOf";
  public static readonly NAMED_INDIVIDUAL = OWL.NAMESPACE + "NamedIndividual";
}
