// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {Namespace} from "@/vocabulary/Namespace";

export class OWL {

  public static readonly PREFIX = "owl"
  public static readonly THING = Namespace.OWL + "Thing"
  public static readonly CLASS = Namespace.OWL + "Class"
  public static readonly EQUIVALENT_CLASS = Namespace.OWL + "equivalentClass"
  public static readonly INTERSECTION_OF = Namespace.OWL + "intersectionOf"
  public static readonly UNION_OF = Namespace.OWL + "unionOf"
  public static readonly RESTRICTION = Namespace.OWL + "Restriction"
  public static readonly ON_PROPERTY = Namespace.OWL + "onProperty"
  public static readonly ON_CLASS = Namespace.OWL + "onClass"
  public static readonly SOME_VALUES_FROM = Namespace.OWL + "someValuesFrom"
  public static readonly ALL_VALUES_FROM = Namespace.OWL + "allValuesFrom"
  public static readonly OBJECT_PROPERTY = Namespace.OWL + "ObjectProperty"
  public static readonly DATATYPE_PROPERTY = Namespace.OWL + "DatatypeProperty"
  public static readonly ANNOTATION_PROPERTY = Namespace.OWL + "AnnotationProperty"
  public static readonly INVERSE_OF = Namespace.OWL + "inverseOf"
  public static readonly INVERSE_OBJECT_PROPERTY = Namespace.OWL + "inverseOf"
  public static readonly PROPERTY_CHAIN = Namespace.OWL + "propertyChainAxiom"
  public static readonly TRANSITIVE = Namespace.OWL + "TransitiveProperty"
  public static readonly FUNCTIONAL = Namespace.OWL + "FunctionalProperty"
  public static readonly SYMMETRIC = Namespace.OWL + "SymmetricProperty"
  public static readonly REFLEXIVE = Namespace.OWL + "ReflexiveProperty"
  public static readonly ON_DATATYPE = Namespace.OWL + "onDatatype"
  public static readonly WITH_RESTRICTIONS = Namespace.OWL + "withRestrictions"
  public static readonly MAX_CARDINALITY = Namespace.OWL + "maxCardinality"
  public static readonly MIN_CARDINALITY = Namespace.OWL + "minCardinality"
  public static readonly ON_DATA_RANGE = Namespace.OWL + "onDataRange"
  public static readonly HAS_VALUE = Namespace.OWL + "hasValue"
  public static readonly COMPLEMENT_OF = Namespace.OWL + "complementOf"
  public static readonly ONE_OF = Namespace.OWL + "oneOf"
  public static readonly NAMED_INDIVIDUAL = Namespace.OWL + "NamedIndividual"
}
