// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator



export class PRSB {

  public static readonly PREFIX = "rs"
}
