// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class QUERY {
  public static readonly DOMAIN = "http://endhealth.info/im#";
  public static readonly NAMESPACE = QUERY.DOMAIN + "Query_";
  public static readonly IS_ALLOWABLE_RANGE = QUERY.NAMESPACE + "IsAllowableRange";
  public static readonly ALLOWABLE_RANGE_SUGGESTIONS = QUERY.NAMESPACE + "AllowableRangeSuggestions";
  public static readonly GET_SUBCLASSES = QUERY.NAMESPACE + "GetSubClasses";
  public static readonly GET_ANCESTORS = QUERY.NAMESPACE + "GetAncestors";
  public static readonly SEARCH_CONTAINED_IN = QUERY.NAMESPACE + "SearchContainedIn";
  public static readonly ALLOWABLE_CHILD_TYPES = QUERY.NAMESPACE + "AllowableChildTypes";
  public static readonly PROPERTY_RANGE = QUERY.NAMESPACE + "PropertyRange";
  public static readonly OBJECT_PROPERTY_RANGE_SUGGESTIONS = QUERY.NAMESPACE + "ObjectPropertyRangeSuggestions";
  public static readonly DATA_PROPERTY_RANGE_SUGGESTIONS = QUERY.NAMESPACE + "DataPropertyRangeSuggestions";
  public static readonly ALLOWABLE_PROPERTIES = QUERY.NAMESPACE + "AllowableProperties";
  public static readonly ALLOWABLE_PROPERTY_ANCESTORS = QUERY.NAMESPACE + "AllowablePropertyAncestors";
  public static readonly IS_VALID_PROPERTY = QUERY.NAMESPACE + "IsValidProperty";
  public static readonly SEARCH_PROPERTIES = QUERY.NAMESPACE + "SearchProperties";
  public static readonly SEARCH_ENTITIES = QUERY.NAMESPACE + "SearchEntities";
  public static readonly SEARCH_FOLDERS = QUERY.NAMESPACE + "SearchFolders";
  public static readonly SEARCH_ALLOWABLE_CONTAINED_IN = QUERY.NAMESPACE + "SearchAllowableContainedIn";
  public static readonly SEARCH_MAIN_TYPES = QUERY.NAMESPACE + "SearchmainTypes";
  public static readonly DM_PROPERTY = QUERY.NAMESPACE + "DataModelPropertyByShape";
  public static readonly SEARCH_ALLOWABLE_SUBCLASS = QUERY.NAMESPACE + "SearchAllowableSubclass";
  public static readonly GET_VALUES_FROM_PROPERTY_RANGE = QUERY.NAMESPACE + "GetValuesFromPropertyRange";
  public static readonly GET_SUBSETS = QUERY.NAMESPACE + "GetSubsets";
}
