// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {Namespace} from "@/vocabulary/Namespace";

export class QUERY {

  public static readonly DOMAIN = "http://endhealth.info/im#"
  public static readonly IS_ALLOWABLE_RANGE = Namespace.IM_QUERY + "IsAllowableRange"
  public static readonly ALLOWABLE_RANGE_SUGGESTIONS = Namespace.IM_QUERY + "AllowableRangeSuggestions"
  public static readonly GET_SUBCLASSES = Namespace.IM_QUERY + "GetSubClasses"
  public static readonly GET_ANCESTORS = Namespace.IM_QUERY + "GetAncestors"
  public static readonly SEARCH_CONTAINED_IN = Namespace.IM_QUERY + "SearchContainedIn"
  public static readonly ALLOWABLE_CHILD_TYPES = Namespace.IM_QUERY + "AllowableChildTypes"
  public static readonly PROPERTY_RANGE = Namespace.IM_QUERY + "PropertyRange"
  public static readonly OBJECT_PROPERTY_RANGE_SUGGESTIONS = Namespace.IM_QUERY + "ObjectPropertyRangeSuggestions"
  public static readonly DATA_PROPERTY_RANGE_SUGGESTIONS = Namespace.IM_QUERY + "DataPropertyRangeSuggestions"
  public static readonly ALLOWABLE_PROPERTIES = Namespace.IM_QUERY + "AllowableProperties"
  public static readonly ALLOWABLE_PROPERTY_ANCESTORS = Namespace.IM_QUERY + "AllowablePropertyAncestors"
  public static readonly IS_VALID_PROPERTY = Namespace.IM_QUERY + "IsValidProperty"
  public static readonly SEARCH_PROPERTIES = Namespace.IM_QUERY + "SearchProperties"
  public static readonly SEARCH_ENTITIES = Namespace.IM_QUERY + "SearchEntities"
  public static readonly SEARCH_FOLDERS = Namespace.IM_QUERY + "SearchFolders"
  public static readonly SEARCH_ALLOWABLE_CONTAINED_IN = Namespace.IM_QUERY + "SearchAllowableContainedIn"
  public static readonly SEARCH_MAIN_TYPES = Namespace.IM_QUERY + "SearchmainTypes"
  public static readonly DM_PROPERTY = Namespace.IM_QUERY + "DataModelPropertyByShape"
  public static readonly SEARCH_ALLOWABLE_SUBCLASS = Namespace.IM_QUERY + "SearchAllowableSubclass"
  public static readonly GET_VALUES_FROM_PROPERTY_RANGE = Namespace.IM_QUERY + "GetValuesFromPropertyRange"
  public static readonly GET_SUBSETS = Namespace.IM_QUERY + "GetSubsets"
}
