// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class RDF {
  public static readonly NAMESPACE = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
  public static readonly PREFIX = "rdf";
  public static readonly TYPE = RDF.NAMESPACE + "type";
  public static readonly PROPERTY = RDF.NAMESPACE + "Property";
  public static readonly LIST = RDF.NAMESPACE + "List";
  public static readonly PREDICATE = RDF.NAMESPACE + "predicate";
  public static readonly SUBJECT = RDF.NAMESPACE + "subject";
  public static readonly OBJECT = RDF.NAMESPACE + "object";
}
