// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {Namespace} from "@/vocabulary/Namespace";

export class RDF {

  public static readonly PREFIX = "rdf"
  public static readonly TYPE = Namespace.RDF + "type"
  public static readonly PROPERTY = Namespace.RDF + "Property"
  public static readonly LIST = Namespace.RDF + "List"
  public static readonly PREDICATE = Namespace.RDF + "predicate"
  public static readonly SUBJECT = Namespace.RDF + "subject"
  public static readonly OBJECT = Namespace.RDF + "object"
}
