// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class RDFS {
  public static readonly NAMESPACE = "http://www.w3.org/2000/01/rdf-schema#";
  public static readonly PREFIX = "rdfs";
  public static readonly LABEL = RDFS.NAMESPACE + "label";
  public static readonly COMMENT = RDFS.NAMESPACE + "comment";
  public static readonly SUBCLASS_OF = RDFS.NAMESPACE + "subClassOf";
  public static readonly SUB_PROPERTY_OF = RDFS.NAMESPACE + "subPropertyOf";
  public static readonly DOMAIN = RDFS.NAMESPACE + "domain";
  public static readonly RANGE = RDFS.NAMESPACE + "range";
  public static readonly RESOURCE = RDFS.NAMESPACE + "Resource";
  public static readonly CLASS = RDFS.NAMESPACE + "Class";
  public static readonly DATATYPE = RDFS.NAMESPACE + "Datatype";
  public static readonly IS_DEFINED_BY = RDFS.NAMESPACE + "isDefinedBy";
}
