// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {Namespace} from "@/vocabulary/Namespace";

export class RDFS {

  public static readonly PREFIX = "rdfs"
  public static readonly LABEL = Namespace.RDFS + "label"
  public static readonly COMMENT = Namespace.RDFS + "comment"
  public static readonly SUBCLASS_OF = Namespace.RDFS + "subClassOf"
  public static readonly SUB_PROPERTY_OF = Namespace.RDFS + "subPropertyOf"
  public static readonly DOMAIN = Namespace.RDFS + "domain"
  public static readonly RANGE = Namespace.RDFS + "range"
  public static readonly RESOURCE = Namespace.RDFS + "Resource"
  public static readonly CLASS = Namespace.RDFS + "Class"
  public static readonly DATATYPE = Namespace.RDFS + "Datatype"
  public static readonly IS_DEFINED_BY = Namespace.RDFS + "isDefinedBy"
}
