// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {Namespace} from "@/vocabulary/Namespace";

export class SNOMED {

  public static readonly DOMAIN = "http://snomed.info/"
  public static readonly PREFIX = "sn"
  public static readonly ATTRIBUTE = Namespace.SNOMED + "246061005"
  public static readonly ANY = Namespace.SNOMED + "*"
}
