// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {Namespace} from "@/vocabulary/Namespace";
import {IM} from "@/vocabulary/IM";

export class TransformFunction {

  public static readonly CONCATENATE = Namespace.IM + "Concatenate"
  public static readonly STRING_JOIN = Namespace.IM + "StringJoin"
  public static readonly SNOMED_CODE_CONCEPT_MAP = Namespace.IM + "SchemedCodeConceptMap"
}
