// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {Namespace} from "@/vocabulary/Namespace";

export class USER {

  public static readonly DOMAIN = "http://endhealth.info/"
  public static readonly PREFIX = "usr"
  public static readonly USER_PRESET = Namespace.USER + "UserPreset"
  public static readonly USER_PRIMARY_COLOR = Namespace.USER + "UserPrimaryColor"
  public static readonly USER_SURFACE_COLOR = Namespace.USER + "UserSurfaceColor"
  public static readonly USER_DARK_MODE = Namespace.USER + "UserDarkMode"
  public static readonly USER_FONT_SIZE = Namespace.USER + "UserFontSize"
  public static readonly USER_MRU = Namespace.USER + "UserMRU"
  public static readonly USER_FAVOURITES = Namespace.USER + "UserFavourites"
  public static readonly ORGANISATIONS = Namespace.USER + "Organisations"
  public static readonly GRAPHS = Namespace.USER + "Graphs"
}
