// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {Namespace} from "@/vocabulary/Namespace";

export class VALIDATION {

  public static readonly DOMAIN = "http://endhealth.info/im#"
  public static readonly IS_DEFINITION = Namespace.IM_VALIDATION + "isDefinition"
  public static readonly HAS_PARENT = Namespace.IM_VALIDATION + "hasParent"
  public static readonly IS_IRI = Namespace.IM_VALIDATION + "isIri"
  public static readonly IS_TERMCODE = Namespace.IM_VALIDATION + "isTermcode"
  public static readonly IS_PROPERTY = Namespace.IM_VALIDATION + "isProperty"
  public static readonly IS_SCHEME = Namespace.IM_VALIDATION + "isScheme"
  public static readonly IS_STATUS = Namespace.IM_VALIDATION + "isStatus"
  public static readonly IS_ROLE_GROUP = Namespace.IM_VALIDATION + "isRoleGroup"
}
