// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {Namespace} from "@/vocabulary/Namespace";

export class WORKFLOW {

  public static readonly DOMAIN = "http://endhealth.info/"
  public static readonly BUG_REPORT = Namespace.WORKFLOW + "bugReport"
  public static readonly DATE_CREATED = Namespace.WORKFLOW + "dateCreated"
  public static readonly CREATED_BY = Namespace.WORKFLOW + "createdBy"
  public static readonly ASSIGNED_TO = Namespace.WORKFLOW + "assignedTo"
  public static readonly STATE = Namespace.WORKFLOW + "state"
  public static readonly HOST_URL = Namespace.WORKFLOW + "hostUrl"
  public static readonly RELATED_PRODUCT = Namespace.WORKFLOW + "relatedProduct"
  public static readonly RELATED_MODULE = Namespace.WORKFLOW + "relatedModule"
  public static readonly OPERATING_SYSTEM = Namespace.WORKFLOW + "operatingSystem"
  public static readonly OPERATING_SYSTEM_OTHER = Namespace.WORKFLOW + "operatingSystemOther"
  public static readonly BROWSER = Namespace.WORKFLOW + "browser"
  public static readonly BROWSER_OTHER = Namespace.WORKFLOW + "browserOther"
  public static readonly SEVERITY = Namespace.WORKFLOW + "severity"
  public static readonly ERROR = Namespace.WORKFLOW + "errorDetails"
  public static readonly REPRODUCE_STEPS = Namespace.WORKFLOW + "reproduceSteps"
  public static readonly EXPECTED_RESULT = Namespace.WORKFLOW + "expectedResult"
  public static readonly ACTUAL_RESULT = Namespace.WORKFLOW + "actualResult"
  public static readonly RELATED_VERSION = Namespace.WORKFLOW + "relatedVersion"
  public static readonly REQUESTED_ROLE = Namespace.WORKFLOW + "requestedRole"
  public static readonly REQUESTED_GRAPH = Namespace.WORKFLOW + "requestedGraph"
  public static readonly APPROVAL_TYPE = Namespace.WORKFLOW + "approvalType"
  public static readonly HISTORY = Namespace.WORKFLOW + "history"
  public static readonly HISTORY_PREDICATE = Namespace.WORKFLOW + "historyPredicate"
  public static readonly HISTORY_ORIGINAL_OBJECT = Namespace.WORKFLOW + "historyOriginalObject"
  public static readonly HISTORY_NEW_OBJECT = Namespace.WORKFLOW + "historyNewObject"
  public static readonly HISTORY_CHANGE_DATE = Namespace.WORKFLOW + "historyChangeDate"
  public static readonly MODIFIED_BY = Namespace.WORKFLOW + "modifiedBy"
}
