// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class WORKFLOW {
  public static readonly DOMAIN = "http://endhealth.info/";
  public static readonly NAMESPACE = WORKFLOW.DOMAIN + "workflow#";
  public static readonly BUG_REPORT = WORKFLOW.NAMESPACE + "bugReport";
  public static readonly DATE_CREATED = WORKFLOW.NAMESPACE + "dateCreated";
  public static readonly CREATED_BY = WORKFLOW.NAMESPACE + "createdBy";
  public static readonly ASSIGNED_TO = WORKFLOW.NAMESPACE + "assignedTo";
  public static readonly STATE = WORKFLOW.NAMESPACE + "state";
  public static readonly RELATED_PRODUCT = WORKFLOW.NAMESPACE + "relatedProduct";
  public static readonly RELATED_MODULE = WORKFLOW.NAMESPACE + "relatedModule";
  public static readonly OPERATING_SYSTEM = WORKFLOW.NAMESPACE + "operatingSystem";
  public static readonly OPERATING_SYSTEM_OTHER = WORKFLOW.NAMESPACE + "operatingSystemOther";
  public static readonly BROWSER = WORKFLOW.NAMESPACE + "browser";
  public static readonly BROWSER_OTHER = WORKFLOW.NAMESPACE + "browserOther";
  public static readonly SEVERITY = WORKFLOW.NAMESPACE + "severity";
  public static readonly ERROR = WORKFLOW.NAMESPACE + "errorDetails";
  public static readonly REPRODUCE_STEPS = WORKFLOW.NAMESPACE + "reproduceSteps";
  public static readonly EXPECTED_RESULT = WORKFLOW.NAMESPACE + "expectedResult";
  public static readonly ACTUAL_RESULT = WORKFLOW.NAMESPACE + "actualResult";
  public static readonly RELATED_VERSION = WORKFLOW.NAMESPACE + "relatedVersion";
  public static readonly REQUESTED_ROLE = WORKFLOW.NAMESPACE + "requestedRole";
  public static readonly APPROVAL_TYPE = WORKFLOW.NAMESPACE + "approvalType";
  public static readonly HISTORY = WORKFLOW.NAMESPACE + "history";
  public static readonly HISTORY_PREDICATE = WORKFLOW.NAMESPACE + "historyPredicate";
  public static readonly HISTORY_ORIGINAL_OBJECT = WORKFLOW.NAMESPACE + "historyOriginalObject";
  public static readonly HISTORY_NEW_OBJECT = WORKFLOW.NAMESPACE + "historyNewObject";
  public static readonly HISTORY_CHANGE_DATE = WORKFLOW.NAMESPACE + "historyChangeDate";
  public static readonly MODIFIED_BY = WORKFLOW.NAMESPACE + "modifiedBy";
}
