// This file is autogenerated. Any edits made will be lost. To make changes, go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

import {Namespace} from "@/vocabulary/Namespace";

export class XSD {

  public static readonly PREFIX = "xsd"
  public static readonly PATTERN = Namespace.XSD + "pattern"
  public static readonly MIN_INCLUSIVE = Namespace.XSD + "minInclusive"
  public static readonly MIN_EXCLUSIVE = Namespace.XSD + "minExclusive"
  public static readonly MAX_INCLUSIVE = Namespace.XSD + "maxInclusive"
  public static readonly MAX_EXCLUSIVE = Namespace.XSD + "maxExclusive"
  public static readonly INTEGER = Namespace.XSD + "integer"
  public static readonly STRING = Namespace.XSD + "string"
  public static readonly BOOLEAN = Namespace.XSD + "boolean"
  public static readonly LONG = Namespace.XSD + "long"
  public static readonly DOUBLE = Namespace.XSD + "double"
  public static readonly DATE_TIME = Namespace.XSD + "dateTime"
  public static readonly NUMBER = Namespace.XSD + "number"
  public static readonly DECIMAL = Namespace.XSD + "decimal"
}
