// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  ECL = 1,
  RefinedConcept = 2,
  Concept = 3,
  Entailment = 4,
  Code = 5,
  Term = 6,
  MultiRefinement = 7,
  SingleRefinement = 8,
  Property = 9,
  Comparator = 10,
  Value = 11,
  Bool = 12,
  MultiRefinementGroup = 13
