// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$[OVQPOOO_QPO'#C_OdQPO'#C_OiQPO'#C^QOQPOOOnQPO,58yOsQPO,58yOxQPO,58xOOQO1G.e1G.eO!TQPO1G.eOOQO'#Ce'#CeO!YQPO'#CdO!_QPO'#CcOVQPO'#CiOOQO1G.d1G.dOOQO7+$P7+$POVQPO,59OOVQPO'#ClO!dQPO,58}O!oQPO,59TOOQO'#Cg'#CgOOQO1G.j1G.jOOQO,59W,59WOOQO-E6j-E6jOOQO1G.o1G.o",
  stateData: "!t~OcOS~OSQOTPO~OdTO~OTUO~OeVO~OUWO~OdXO~OSQOTPO^]O~OU_O~OY`O~O[aO~O[aOaVa_Va~O_hO~O",
  goto: "!`aPPbePPPpv}P!SP!VPP!YRSOQROUYV]aRd`Q^VRc]S[V]RfaVZV]aRe`R^VQb[Rgb",
  nodeNames: "⚠ ECL RefinedConcept Concept Entailment Code Term MultiRefinement SingleRefinement Property Comparator Value Bool MultiRefinementGroup ( )",
  maxTerm: 21,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "'_~RfX^!gpq!gqr#[rs#gxy%Tyz%Y!Q![%_!^!_%g!_!`#b!`!a%t!c!d%|!q!r&_!y!z&e#p#q'Y#y#z!g$f$g!g#BY#BZ!g$IS$I_!g$I|$JO!g$JT$JU!g$KV$KW!g&FU&FV!g~!lYc~X^!gpq!g#y#z!g$f$g!g#BY#BZ!g$IS$I_!g$I|$JO!g$JT$JU!g$KV$KW!g&FU&FV!g~#_P!_!`#b~#gOY~~#jVOr#grs$Ps#O#g#O#P$U#P;'S#g;'S;=`$}<%lO#g~$UOU~~$XRO;'S#g;'S;=`$b;=`O#g~$eWOr#grs$Ps#O#g#O#P$U#P;'S#g;'S;=`$};=`<%l#g<%lO#g~%QP;=`<%l#g~%YO^~~%_O_~~%dPT~!Q![%_~%lPS~!^!_%o~%tOS~~%yPS~!`!a%o~&PP!p!q&S~&VP!f!g&Y~&_O[~~&bP!t!u&Y~&hP!j!k&k~&nP!g!h&q~&tP!t!u&w~&zP!g!h&}~'QPpq'T~'YOe~~'_Od~",
  tokenizers: [0],
  topRules: {"ECL":[0,1]},
  tokenPrec: 0
})
