// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$UOVQPOOO_QPO'#C^OdQPO'#C^OiQPO'#CoOOQO'#Co'#CoQOQPOOOOQO,58x,58xOqQPO,58xOvQPO,58|OOQO1G.d1G.dOOQO'#Cf'#CfO!RQPO'#CeO!WQPO'#CdOVQPO'#CjOOQO1G.h1G.hOVQPO,59POVQPO'#CkO!]QPO,59OO!hQPO,59UOOQO'#Ch'#ChOOQO1G.k1G.kOOQO,59V,59VOOQO-E6i-E6iOOQO1G.p1G.p",
  stateData: "!m~ObOS~ORQOSPO~OTUO~OSVO~OVWO`cX~OTXO~ORQOSPOd]O~OZ_O~O]`O~O]`O`WaeWa~OegO~O",
  goto: "!fdPPePPPpPsy!QP!VP!Y!]PPP!cQROUYW]`Rc_RSOQ^WRb]S[W]Re`VZW]`Rd_R^WQa[RfaRTO",
  nodeNames: "⚠ ECL Concept Entailment Term Code RefinedConcept Refine MultiRefinement SingleRefinement Property Comparator Value Bool MultiRefinementGroup",
  maxTerm: 21,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "+[~RlX^!ypq!yqr#nrs#yxy%gyz%l!^!_%q!_!`#t!`!a&O!c!d&W!j!k&r!k!l(S!q!r(]!y!z(f!}#O*T#T#U*i#[#]*o#]#^*u#c#d*{#k#l+R#y#z!y$f$g!y#BY#BZ!y$IS$I_!y$I|$JO!y$JT$JU!y$KV$KW!y&FU&FV!y~#OYb~X^!ypq!y#y#z!y$f$g!y#BY#BZ!y$IS$I_!y$I|$JO!y$JT$JU!y$KV$KW!y&FU&FV!y~#qP!_!`#t~#yOZ~~#|VOr#yrs$cs#O#y#O#P$h#P;'S#y;'S;=`%a<%lO#y~$hOS~~$kRO;'S#y;'S;=`$t;=`O#y~$wWOr#yrs$cs#O#y#O#P$h#P;'S#y;'S;=`%a;=`<%l#y<%lO#y~%dP;=`<%l#y~%lOd~~%qOe~~%vPR~!^!_%y~&OOR~~&TPR~!`!a%y~&ZQ!p!q&a#b#c&l~&dP!f!g&g~&lO]~~&oP#W#X&g~&uQ!c!d&{#T#U'j~'OP!x!y'R~'UP!k!l'X~'[P!p!q'_~'bP!i!j'e~'jOV~~'mP#j#k'p~'sP#]#^'v~'yP#b#c'|~(PP#Z#['e~(VQ!h!i'e#Y#Z'e~(`Q!t!u&g#f#g&g~(iS!j!k(u!k!l)X#[#])e#]#^)w~(xP!g!h({~)OP!t!u)R~)UP!g!h'e~)[P!v!w)_~)bP!j!k'e~)hP#X#Y)k~)nP#f#g)q~)tP#X#Y'e~)zP#h#i)}~*QP#[#]'e~*WP!Q![*Z~*^Q!Q![*Z#P#Q*d~*iOT~~*lP#b#c&l~*rP#T#U'j~*xP#Y#Z'e~+OP#f#g&g~+UQ#[#])e#]#^)w",
  tokenizers: [0],
  topRules: {"ECL":[0,1]},
  tokenPrec: 0
})
