// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  ECL = 1,
  Concept = 2,
  Entailment = 3,
  Term = 4,
  Code = 5,
  RefinedConcept = 6,
  Refine = 7,
  MultiRefinement = 8,
  SingleRefinement = 9,
  Property = 10,
  Comparator = 11,
  Value = 12,
  Bool = 13,
  MultiRefinementGroup = 14
