// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator 

export class CONFIG {

	public static readonly NAMESPACE = "http://endhealth.info/config#";
	public static readonly DOMAIN = "http://endhealth.info/";
	public static readonly PREFIX = "cfg";
	public static readonly DEFINITION = CONFIG.NAMESPACE + "definition";
	public static readonly SUMMARY = CONFIG.NAMESPACE + "summary";
	public static readonly FILTER_DEFAULTS = CONFIG.NAMESPACE + "filterDefaults";
	public static readonly INFERRED_PREDICATES = CONFIG.NAMESPACE + "inferredPredicates";
	public static readonly INFERRED_EXCLUDE_PREDICATES = CONFIG.NAMESPACE + "inferredExcludePredicates";
	public static readonly CONCEPT_DASHBOARD = CONFIG.NAMESPACE + "CONCEPT_DASHBOARD";
	public static readonly DEFAULT_PREDICATE_NAMES = CONFIG.NAMESPACE + "defaultPredicateNames";
	public static readonly XML_SCHEMA_DATA_TYPES = CONFIG.NAMESPACE + "xmlSchemaDataTypes";
	public static readonly DEFAULT_PREFIXES = CONFIG.NAMESPACE + "defaultPrefixes";
	public static readonly GRAPH_EXCLUDE_PREDICATES = CONFIG.NAMESPACE + "graphExcludePredicates";
	public static readonly IM1_PUBLISH = CONFIG.NAMESPACE + "im1Publish";
	public static readonly IMDIRECTORY_LATEST_RELEASE = CONFIG.NAMESPACE + "IMDirectoryLatestRelease";
	public static readonly IMDIRECTORY_ALL_RELEASES = CONFIG.NAMESPACE + "IMDirectoryAllReleases";
	public static readonly IMPORT_DATA_LATEST_RELEASE = CONFIG.NAMESPACE + "ImportDataLatestRelease";
	public static readonly IMPORT_DATA_ALL_RELEASES = CONFIG.NAMESPACE + "ImportDataAllReleases";
}