import { IM } from "../interfaces/AutoGen";
import { OWL } from "../interfaces/AutoGen";
import { RDF } from "../interfaces/AutoGen";
import { RDFS } from "../interfaces/AutoGen";
import { SHACL } from "../interfaces/AutoGen";
import { SNOMED } from "../interfaces/AutoGen";
import { CONFIG } from "../interfaces/AutoGen";
import { XSD } from "../interfaces/AutoGen";
import { USER } from "../interfaces/AutoGen";
import { WORKFLOW } from "../interfaces/AutoGen";
import { FHIR } from "../interfaces/AutoGen";
import { MAP } from "../interfaces/AutoGen";
import { ODS } from "../interfaces/AutoGen";
import { ORG } from "../interfaces/AutoGen";
import { PRSB } from "../interfaces/AutoGen";
import { QR } from "../interfaces/AutoGen";
import { COMPONENT } from "../interfaces/AutoGen";
import { EDITOR } from "../interfaces/AutoGen";
import { FUNCTION } from "../interfaces/AutoGen";
import { GRAPH } from "../interfaces/AutoGen";
import { VALIDATION } from "../interfaces/AutoGen";
import { QUERY } from "../interfaces/AutoGen";

export { IM, OWL, RDF, RDFS, SHACL, SNOMED, CONFIG, XSD, USER, WORKFLOW, FHIR, FUNCTION, MAP, ODS, ORG, PRSB, QR, QUERY, COMPONENT, EDITOR, GRAPH, VALIDATION };
