// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class ORG {
  public static readonly ORGANISATION_NAMESPACE = "http://org.endhealth.info/im#";
  public static readonly LOCATION_NAMESPACE = "http://loc.endhealth.info/im#";
  public static readonly ORGANISATION_RECORD_CLASS = "http://endhealth.info/im#organisationRecordClass";
  public static readonly RELATED_ORGANISATION = "http://endhealth.info/im#organisationRelationship";
  public static readonly TARGET = "http://endhealth.info/im#targetOrganisation";
  public static readonly ROLE = "http://endhealth.info/im#organisationRole";
  public static readonly ODS_CODE = "http://endhealth.info/im#odsCode";
}
