// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class SHACL {
  public static readonly NAMESPACE = "http://www.w3.org/ns/shacl#";
  public static readonly PREFIX = "sh";
  public static readonly PATH = SHACL.NAMESPACE + "path";
  public static readonly MININCLUSIVE = SHACL.NAMESPACE + "minInclusive";
  public static readonly MINEXCLUSIVE = SHACL.NAMESPACE + "minExclusive";
  public static readonly MAXINCLUSIVE = SHACL.NAMESPACE + "maxInclusive";
  public static readonly MAXEXCLUSIVE = SHACL.NAMESPACE + "maxExclusive";
  public static readonly PROPERTY = SHACL.NAMESPACE + "property";
  public static readonly PROPERTY_GROUP = SHACL.NAMESPACE + "PropertyGroup";
  public static readonly MINCOUNT = SHACL.NAMESPACE + "minCount";
  public static readonly MAXCOUNT = SHACL.NAMESPACE + "maxCount";
  public static readonly VALUE = SHACL.NAMESPACE + "value";
  public static readonly PATTERN = SHACL.NAMESPACE + "pattern";
  public static readonly INVERSEPATH = SHACL.NAMESPACE + "inversePath";
  public static readonly CLASS = SHACL.NAMESPACE + "class";
  public static readonly DATATYPE = SHACL.NAMESPACE + "datatype";
  public static readonly SPARQL = SHACL.NAMESPACE + "sparql";
  public static readonly SELECT = SHACL.NAMESPACE + "select";
  public static readonly PARAMETER = SHACL.NAMESPACE + "parameter";
  public static readonly IRI = SHACL.NAMESPACE + "IRI";
  public static readonly OPTIONAL = SHACL.NAMESPACE + "optional";
  public static readonly NODESHAPE = SHACL.NAMESPACE + "NodeShape";
  public static readonly TARGETCLASS = SHACL.NAMESPACE + "targetClass";
  public static readonly NODE = SHACL.NAMESPACE + "node";
  public static readonly ORDER = SHACL.NAMESPACE + "order";
  public static readonly OR = SHACL.NAMESPACE + "or";
  public static readonly NOT = SHACL.NAMESPACE + "not";
  public static readonly NODE_KIND = SHACL.NAMESPACE + "nodeKind";
  public static readonly PROPERTYSHAPE = SHACL.NAMESPACE + "PropertyShape";
  public static readonly AND = SHACL.NAMESPACE + "and";
  public static readonly NODES = SHACL.NAMESPACE + "nodes";
  public static readonly TARGET_TYPE = SHACL.NAMESPACE + "targetType";
  public static readonly TARGET = SHACL.NAMESPACE + "target";
  public static readonly SPARQL_TARGET = SHACL.NAMESPACE + "SPARQLTarget";
  public static readonly FUNCTION = SHACL.NAMESPACE + "Function";
  public static readonly RETURN_TYPE = SHACL.NAMESPACE + "returnType";
  public static readonly GROUP = SHACL.NAMESPACE + "group";
  public static readonly NAME = SHACL.NAMESPACE + "name";
  public static readonly EXPRESSION = SHACL.NAMESPACE + "expression";
  public static readonly HAS_VALUE = SHACL.NAMESPACE + "hasValue";
}
