// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class SNOMED {
  public static readonly DOMAIN = "http://snomed.info/";
  public static readonly NAMESPACE = SNOMED.DOMAIN + "sct#";
  public static readonly PREFIX = "sn";
  public static readonly ATTRIBUTE = SNOMED.NAMESPACE + "246061005";
  public static readonly ANY = SNOMED.NAMESPACE + "*";
}
