// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class VALIDATION {
  public static readonly DOMAIN = "http://endhealth.info/im#";
  public static readonly NAMESPACE = VALIDATION.DOMAIN + "Validation_";
  public static readonly IS_DEFINITION = VALIDATION.NAMESPACE + "isDefinition";
  public static readonly HAS_PARENT = VALIDATION.NAMESPACE + "hasParent";
  public static readonly IS_IRI = VALIDATION.NAMESPACE + "isIri";
  public static readonly IS_TERMCODE = VALIDATION.NAMESPACE + "isTermcode";
  public static readonly IS_PROPERTY = VALIDATION.NAMESPACE + "isProperty";
  public static readonly IS_SCHEME = VALIDATION.NAMESPACE + "isScheme";
  public static readonly IS_STATUS = VALIDATION.NAMESPACE + "isStatus";
  public static readonly IS_ROLE_GROUP = VALIDATION.NAMESPACE + "isRoleGroup";
}
