// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class XS {
  public static readonly NAMESPACE = "http://www.w3.org/2001/XMLSchema#";
  public static readonly PREFIX = "xs";
  public static readonly PATTERN = XS.NAMESPACE + "pattern";
  public static readonly MIN_INCLUSIVE = XS.NAMESPACE + "minInclusive";
  public static readonly MIN_EXCLUSIVE = XS.NAMESPACE + "minExclusive";
  public static readonly MAX_INCLUSIVE = XS.NAMESPACE + "maxInclusive";
  public static readonly MAX_EXCLUSIVE = XS.NAMESPACE + "maxExclusive";
  public static readonly INTEGER = XS.NAMESPACE + "integer";
  public static readonly STRING = XS.NAMESPACE + "string";
  public static readonly BOOLEAN = XS.NAMESPACE + "boolean";
  public static readonly LONG = XS.NAMESPACE + "long";
  public static readonly DOUBLE = XS.NAMESPACE + "double";
  public static readonly DATE_TIME = XS.NAMESPACE + "dateTime";
}
