// This file is autogenerated. Any edits made will be lost. To make changes go to imapi/api/vocab.json and re-run gradle task staticConstGenerator

export class XSD {
  public static readonly NAMESPACE = "http://www.w3.org/2001/XMLSchema#";
  public static readonly PREFIX = "xsd";
  public static readonly PATTERN = XSD.NAMESPACE + "pattern";
  public static readonly MININCLUSIVE = XSD.NAMESPACE + "minInclusive";
  public static readonly MINEXCLUSIVE = XSD.NAMESPACE + "minExclusive";
  public static readonly MAXINCLUSIVE = XSD.NAMESPACE + "maxInclusive";
  public static readonly MAXEXCLUSIVE = XSD.NAMESPACE + "maxExclusive";
  public static readonly INTEGER = XSD.NAMESPACE + "integer";
  public static readonly STRING = XSD.NAMESPACE + "string";
  public static readonly BOOLEAN = XSD.NAMESPACE + "boolean";
  public static readonly LONG = XSD.NAMESPACE + "long";
  public static readonly DOUBLE = XSD.NAMESPACE + "double";
}
