TEST_USERNAME=cypress
TEST_PASSWORD=uzv6duKjAf6F!zqL
TEST_AUTH_URL="http://localhost:8000/login/oauth/authorize"
APP_URL=http://localhost:8082

headless_chrome = true
gauge_reports_dir = docs/test_reports
overwrite_reports = true
screenshot_on_failure = true
logs_directory = docs/logs
gauge_specs_dir = docs/specs
csv_delimiter = ,
allow_multiline_step = false
test_timeout = 40000
DEBUG = false
STEP_IMPL_DIR = tests/gauge