APP_URL=http://localhost:8082

headless_chrome = false
gauge_reports_dir = tests/e2e/outputs/test_reports
overwrite_reports = true
screenshot_on_failure = true
logs_directory = tests/e2e/outputs/logs
gauge_specs_dir = tests/e2e/specs
gauge_screenshots_dir = tests/e2e/outputs/screenshots
csv_delimiter = ,
allow_multiline_step = false
test_timeout = 40000
DEBUG = false
STEP_IMPL_DIR = tests/e2e/implementations
