const ENV_SOURCE: any = "production" === process.env.NODE_ENV ? process.env : import.meta.env;

const Env = {
  API: ENV_SOURCE.VITE_API ?? "http://localhost:8080/",
  GIT_TOKEN: ENV_SOURCE.VITE_GIT_TOKEN,
  GRAPH_HOST: ENV_SOURCE.VITE_GRAPH_HOST ?? "http://localhost:7200",
  GRAPH_REPO: ENV_SOURCE.VITE_GRAPH_REPO ?? "im",
  GRAPH_REPO_CONFIG: ENV_SOURCE.VITE_GRAPH_REPO_CONFIG ?? "config",
  GRAPH_REPO_USER: ENV_SOURCE.VITE_GRAPH_REPO_USER ?? "user",
  GRAPH_REPO_WORKFLOW: ENV_SOURCE.VITE_GRAPH_REPO_WORKFLOW ?? "workflow",
  GRAPH_TIMEOUT: ENV_SOURCE.VITE_GRAPH_TIMEOUT ?? 30000,
  OPENSEARCH_URL: ENV_SOURCE.VITE_OPENSEARCH_URL ?? "https://search.endeavourhealth.net/concept/_search",
  OPENSEARCH_AUTH: ENV_SOURCE.VITE_OPENSEARCH_AUTH ?? "",
  COGNITO_REGION: ENV_SOURCE.VITE_COGNITO_REGION ?? "eu-west-2",
  COGNITO_USER_POOL: ENV_SOURCE.VITE_COGNITO_USER_POOL ?? "",
  ALLOWED_HOSTS: ENV_SOURCE.VITE_ALLOWED_HOSTS ?? "*"
};

export default Env;
