/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:a9f46df7-f27e-4cc5-827b-d573ecf20667",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_Vt5ScFwss",
    "aws_user_pools_web_client_id": "57ihu3fqv3tidnj99dc5uicrgl",
    "oauth": {}
};


export default awsmobile;
